package vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class PaginaActualizacion extends javax.swing.JFrame {

    /**
     * Creates new form PaginaActualizacion
     */
    public PaginaActualizacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_cliente = new javax.swing.JLabel();
        listaclientes = new javax.swing.JComboBox<>();
        btn_seleccionar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        lb_direccion = new javax.swing.JLabel();
        lb_fechavenc = new javax.swing.JLabel();
        lb_placas = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        lb_titulo_act = new javax.swing.JLabel();
        lb_fechainic = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        lb_eliminar = new javax.swing.JLabel();
        lb_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_cliente.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 1, 14)); // NOI18N
        lb_cliente.setText("Cliente a editar");
        jPanel1.add(lb_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        listaclientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(listaclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        btn_seleccionar.setText("Seleccionar");
        btn_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_seleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 130, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 130, -1));

        lb_direccion.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 1, 14)); // NOI18N
        lb_direccion.setText("Dirección cliente");
        jPanel1.add(lb_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, 20));

        lb_fechavenc.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 1, 14)); // NOI18N
        lb_fechavenc.setText("Fecha de vencimiento");
        jPanel1.add(lb_fechavenc, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        lb_placas.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 1, 14)); // NOI18N
        lb_placas.setText("Placas del vehículo");
        jPanel1.add(lb_placas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 130, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 130, -1));

        lb_titulo_act.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 1, 14)); // NOI18N
        lb_titulo_act.setText("Actualización de registros");
        jPanel1.add(lb_titulo_act, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        lb_fechainic.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 1, 14)); // NOI18N
        lb_fechainic.setText("Fecha de inicio");
        jPanel1.add(lb_fechainic, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        btn_guardar.setText("Guardar cambios");
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        lb_eliminar.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 1, 14)); // NOI18N
        lb_eliminar.setText("Eliminar este registro");
        jPanel1.add(lb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lb_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teal2.jpg"))); // NOI18N
        lb_fondo.setText("jLabel8");
        jPanel1.add(lb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_seleccionarActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaActualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaActualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaActualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaActualizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaActualizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_seleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lb_cliente;
    private javax.swing.JLabel lb_direccion;
    private javax.swing.JLabel lb_eliminar;
    private javax.swing.JLabel lb_fechainic;
    private javax.swing.JLabel lb_fechavenc;
    private javax.swing.JLabel lb_fondo;
    private javax.swing.JLabel lb_placas;
    private javax.swing.JLabel lb_titulo_act;
    private javax.swing.JComboBox<String> listaclientes;
    // End of variables declaration//GEN-END:variables
}
