package vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Paginaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Paginaprincipal
     */
    
    
    
    public Paginaprincipal() {
        initComponents();
        this.initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listaclientes = new javax.swing.JComboBox<>();
        listavehiculos = new javax.swing.JComboBox<>();
        listafacturas = new javax.swing.JComboBox<>();
        listapolizas = new javax.swing.JComboBox<>();
        clientesabuscar = new javax.swing.JComboBox<>();
        btn_editar_registro = new javax.swing.JToggleButton();
        btn_consultar = new javax.swing.JButton();
        lb_usuarios_select = new javax.swing.JLabel();
        lb_polizas_select = new javax.swing.JLabel();
        lb_facturas_select = new javax.swing.JLabel();
        lb_vehiculos_select = new javax.swing.JLabel();
        lb_clientes_select = new javax.swing.JLabel();
        lb_proyectotitulo = new javax.swing.JLabel();
        lb_resultado_consultas = new javax.swing.JLabel();
        lb_mostrar_consultas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lb_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaclientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaclientesActionPerformed(evt);
            }
        });
        jPanel1.add(listaclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        listavehiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listavehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listavehiculosActionPerformed(evt);
            }
        });
        jPanel1.add(listavehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        listafacturas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listafacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listafacturasActionPerformed(evt);
            }
        });
        jPanel1.add(listafacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        listapolizas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listapolizas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listapolizasActionPerformed(evt);
            }
        });
        jPanel1.add(listapolizas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        clientesabuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clientesabuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesabuscarActionPerformed(evt);
            }
        });
        jPanel1.add(clientesabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        btn_editar_registro.setText("Editar registros");
        btn_editar_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_registroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        btn_consultar.setText("Consultar");
        jPanel1.add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, -1, -1));

        lb_usuarios_select.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        lb_usuarios_select.setText("Usuarios a consultar");
        jPanel1.add(lb_usuarios_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, 30));

        lb_polizas_select.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        lb_polizas_select.setText("Polizas");
        jPanel1.add(lb_polizas_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, 30));

        lb_facturas_select.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        lb_facturas_select.setText("Facturas");
        jPanel1.add(lb_facturas_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, 30));

        lb_vehiculos_select.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        lb_vehiculos_select.setText("Vehiculos");
        jPanel1.add(lb_vehiculos_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 30));

        lb_clientes_select.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        lb_clientes_select.setText("Clientes");
        jPanel1.add(lb_clientes_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 30));

        lb_proyectotitulo.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        lb_proyectotitulo.setText("Proyecto Java avanzado");
        lb_proyectotitulo.setMaximumSize(new java.awt.Dimension(140, 20));
        lb_proyectotitulo.setMinimumSize(new java.awt.Dimension(140, 20));
        lb_proyectotitulo.setName(""); // NOI18N
        jPanel1.add(lb_proyectotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, 30));

        lb_resultado_consultas.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lb_resultado_consultas.setText("Resultado de consultas");
        jPanel1.add(lb_resultado_consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));
        jPanel1.add(lb_mostrar_consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 247, 580, 170));

        jPanel2.setBackground(new java.awt.Color(229, 191, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 45, 71)));
        jPanel2.setForeground(new java.awt.Color(165, 143, 143));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 590, 180));

        lb_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondomorado_1.jpg"))); // NOI18N
        jPanel1.add(lb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void listaclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaclientesActionPerformed

    private void listapolizasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listapolizasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listapolizasActionPerformed

    private void listavehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listavehiculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listavehiculosActionPerformed

    private void listafacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listafacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listafacturasActionPerformed

    private void clientesabuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesabuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientesabuscarActionPerformed

    private void btn_editar_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_registroActionPerformed
        // TODO add your handling code here:
        PaginaActualizacion actualreg = new PaginaActualizacion();
        actualreg.setVisible(true);
    }//GEN-LAST:event_btn_editar_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paginaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paginaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paginaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paginaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paginaprincipal().setVisible(true);
            }
        });
    }
    
    
    /*
    las listas siguientes contienen los atributos para cada entidad (tabla), la ultima
    contiene los nombres de todos los clientes y la opcion para seleccionar a todos
    
    la opcion ninguno de cada lista excluye esta entidad de la consulta, mientras que todo
    muestra todos los atributos
    */

    


    private void initialize(){
        
        listaclientes.removeAllItems();
        listafacturas.removeAllItems();
        listapolizas.removeAllItems();
        clientesabuscar.removeAllItems();
        listavehiculos.removeAllItems();
        listaclientes.addItem("-Ninguno-");
        listaclientes.addItem("-Todo-");
        listaclientes.addItem("Nombre");
        listaclientes.addItem("Dirección");
        listafacturas.addItem("-Ninguno-");
        listafacturas.addItem("Monto");
        listapolizas.addItem("-Ninguno-");
        listapolizas.addItem("-Todo-");
        listapolizas.addItem("Costo");
        listapolizas.addItem("Prima");
        listapolizas.addItem("Apertura");
        listapolizas.addItem("Vencimiento");
        listavehiculos.addItem("-Ninguno-");
        listavehiculos.addItem("-Todo-");
        listavehiculos.addItem("Placas");
        listavehiculos.addItem("Marca");
        listavehiculos.addItem("Modelo");
        clientesabuscar.addItem("-Todos-"); //se debe elegir al menos un cliente
        
}
    
    public void llenarClientes(){ //EMANUEL hay que definir este metodo
        /*
        esta funcion toma los clientes de las tablas sql y los inserta en la ultima lista de la 
        interfaz, con esa lista se selecciona para que clientes se desea hacer la consulta 
        */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultar;
    private javax.swing.JToggleButton btn_editar_registro;
    private javax.swing.JComboBox<String> clientesabuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_clientes_select;
    private javax.swing.JLabel lb_facturas_select;
    private javax.swing.JLabel lb_fondo;
    private javax.swing.JLabel lb_mostrar_consultas;
    private javax.swing.JLabel lb_polizas_select;
    private javax.swing.JLabel lb_proyectotitulo;
    private javax.swing.JLabel lb_resultado_consultas;
    private javax.swing.JLabel lb_usuarios_select;
    private javax.swing.JLabel lb_vehiculos_select;
    private javax.swing.JComboBox<String> listaclientes;
    private javax.swing.JComboBox<String> listafacturas;
    private javax.swing.JComboBox<String> listapolizas;
    private javax.swing.JComboBox<String> listavehiculos;
    // End of variables declaration//GEN-END:variables
}

