package vista;

import java.util.ArrayList;
import modelo.Modelo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Paginaprincipal
     */
    
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_listaconsultas_ind = new javax.swing.JComboBox<>();
        btn_editar_registro = new javax.swing.JToggleButton();
        btn_consultar_indice = new javax.swing.JButton();
        lb_clientes_select = new javax.swing.JLabel();
        lb_proyectotitulo = new javax.swing.JLabel();
        lb_clientes_select1 = new javax.swing.JLabel();
        lb_resultado_consultas = new javax.swing.JLabel();
        lb_mostrar_consultas = new javax.swing.JLabel();
        jl_listaclientes = new javax.swing.JComboBox<>();
        jl_listaconsultas = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btn_consultar_todos = new javax.swing.JButton();
        lb_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_listaconsultas_ind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jl_listaconsultas_ind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jl_listaconsultas_indActionPerformed(evt);
            }
        });
        jPanel1.add(jl_listaconsultas_ind, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 500, 30));

        btn_editar_registro.setText("Editar registros");
        btn_editar_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_registroActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        btn_consultar_indice.setText("Consultar por ind.");
        btn_consultar_indice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_indiceActionPerformed(evt);
            }
        });
        jPanel1.add(btn_consultar_indice, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, -1, 30));

        lb_clientes_select.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        lb_clientes_select.setText("Consultas para clientes en especifico");
        jPanel1.add(lb_clientes_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 30));

        lb_proyectotitulo.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        lb_proyectotitulo.setText("Proyecto Java avanzado");
        lb_proyectotitulo.setMaximumSize(new java.awt.Dimension(140, 20));
        lb_proyectotitulo.setMinimumSize(new java.awt.Dimension(140, 20));
        lb_proyectotitulo.setName(""); // NOI18N
        jPanel1.add(lb_proyectotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, 30));

        lb_clientes_select1.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        lb_clientes_select1.setText("Consultas para todos los clientes ");
        jPanel1.add(lb_clientes_select1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 30));

        lb_resultado_consultas.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lb_resultado_consultas.setText("Resultado de consultas");
        jPanel1.add(lb_resultado_consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));
        jPanel1.add(lb_mostrar_consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 247, 580, 170));

        jl_listaclientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jl_listaclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jl_listaclientesActionPerformed(evt);
            }
        });
        jPanel1.add(jl_listaclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 190, 30));

        jl_listaconsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jl_listaconsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jl_listaconsultasActionPerformed(evt);
            }
        });
        jPanel1.add(jl_listaconsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 590, 30));

        jPanel2.setBackground(new java.awt.Color(229, 191, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 45, 71)));
        jPanel2.setForeground(new java.awt.Color(165, 143, 143));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 590, 180));

        btn_consultar_todos.setText("Consultar");
        btn_consultar_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultar_todosActionPerformed(evt);
            }
        });
        jPanel1.add(btn_consultar_todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        lb_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/fondomorado_1.jpg"))); // NOI18N
        jPanel1.add(lb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jl_listaconsultas_indActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jl_listaconsultas_indActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_listaconsultas_indActionPerformed

    private void btn_editar_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_registroActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btn_editar_registroActionPerformed

    private void btn_consultar_indiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_indiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar_indiceActionPerformed

    private void jl_listaclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jl_listaclientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_listaclientesActionPerformed

    private void jl_listaconsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jl_listaconsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_listaconsultasActionPerformed

    private void btn_consultar_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultar_todosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_consultar_todosActionPerformed

    
    
    //main, no modificar
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
    
    
    /*
    las listas siguientes contienen los atributos para cada entidad (tabla), la ultima
    contiene los nombres de todos los clientes y la opcion para seleccionar a todos
    
    la opcion ninguno de cada lista excluye esta entidad de la consulta, mientras que todo
    muestra todos los atributos
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_consultar_indice;
    public javax.swing.JButton btn_consultar_todos;
    public javax.swing.JToggleButton btn_editar_registro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JComboBox<String> jl_listaclientes;
    public javax.swing.JComboBox<String> jl_listaconsultas;
    public javax.swing.JComboBox<String> jl_listaconsultas_ind;
    public javax.swing.JLabel lb_clientes_select;
    public javax.swing.JLabel lb_clientes_select1;
    public javax.swing.JLabel lb_fondo;
    public javax.swing.JLabel lb_mostrar_consultas;
    public javax.swing.JLabel lb_proyectotitulo;
    public javax.swing.JLabel lb_resultado_consultas;
    // End of variables declaration//GEN-END:variables
}

